// Analyst: NasoSan | Dev: Claude AI
// Licenza: CC BY 4.0 – nasosan.it | https://creativecommons.org/licenses/by/4.0/

const { withAppBuildGradle, withAndroidManifest, withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

var M3V = "1.4.1";
var SERVICE_CLASS = "com.nasosan.nasosanplayer.NasoSanPlaybackService";

// ── 1. Gradle deps ────────────────────────────────────────────────────────────
function withGradleDeps(config) {
    return withAppBuildGradle(config, function(config) {
        var c = config.modResults.contents;
        // Rimuove versioni media3 esistenti (aggiornamento idempotente)
        c = c.replace(/\n\s*implementation\("androidx\.media3:[^"]*"\)/g, "");
        c = c.replace(/dependencies\s*\{/, [
            "dependencies {",
            '    implementation("androidx.media3:media3-exoplayer:' + M3V + '")',
            '    implementation("androidx.media3:media3-session:' + M3V + '")',
        ].join("\n"));
        // Rimuove vecchie dipendenze
        c = c.replace(/\n\s*implementation\("[^"]*ffmpeg-kit[^"]*"\)/g, "");
        c = c.replace(/\n\s*implementation\("androidx\.media:media:[^"]*"\)/g, "");
        if (!c.includes("libc++_shared.so")) {
            c = c.replace(/android\s*\{/,
                "android {\n    packagingOptions {\n" +
                "        pickFirst 'lib/x86/libc++_shared.so'\n" +
                "        pickFirst 'lib/x86_64/libc++_shared.so'\n" +
                "        pickFirst 'lib/armeabi-v7a/libc++_shared.so'\n" +
                "        pickFirst 'lib/arm64-v8a/libc++_shared.so'\n    }"
            );
        }
        config.modResults.contents = c;
        return config;
    });
}

// ── 2. AndroidManifest ────────────────────────────────────────────────────────
function withManifest(config) {
    return withAndroidManifest(config, function(config) {
        var manifest = config.modResults.manifest;
        if (!manifest.queries) manifest.queries = [];
        if (!manifest.queries[0]) manifest.queries[0] = {};
        if (!manifest.queries[0]["package"]) manifest.queries[0]["package"] = [];
        var hasQuery = manifest.queries[0]["package"].some(function(p) {
            return p.$ && p.$["android:name"] === "co.speechnotes.speechnotes";
        });
        if (!hasQuery) {
            manifest.queries[0]["package"].push({ $: { "android:name": "co.speechnotes.speechnotes" } });
        }
        var app = manifest.application[0];
        if (!app["meta-data"]) app["meta-data"] = [];
        var hasMeta = app["meta-data"].some(function(m) {
            return m.$ && m.$["android:name"] === "com.google.android.gms.car.application";
        });
        if (!hasMeta) {
            app["meta-data"].push({
                $: {
                    "android:name": "com.google.android.gms.car.application",
                    "android:resource": "@xml/automotive_app_desc",
                },
            });
        }
        if (!app.service) app.service = [];
        app.service = app.service.filter(function(s) {
            if (!s.$) return true;
            var n = s.$["android:name"];
            // Rimuove vecchie versioni del nostro service e MusicService di RNTP
            // (RNTP non usa setupPlayer() — il suo service crasherebbe causando backoff Android)
            return n !== "com.nasosan.nasosanplayer.NasoSanBrowserService"
                && n !== SERVICE_CLASS
                && n !== "com.doublesymmetry.trackplayer.service.MusicService";
        });
        app.service.push({
            $: {
                "android:name": SERVICE_CLASS,
                "android:foregroundServiceType": "mediaPlayback",
                "android:exported": "true",
            },
            "intent-filter": [
                {
                    action: [
                        { $: { "android:name": "androidx.media3.session.MediaLibraryService" } },
                    ],
                },
                {
                    action: [
                        { $: { "android:name": "android.media.browse.MediaBrowserService" } },
                    ],
                },
            ],
        });
        return config;
    });
}

// ── 3. automotive_app_desc.xml ────────────────────────────────────────────────
function withAutomotiveXml(config) {
    return withDangerousMod(config, ["android", function(config) {
        var xmlDir = path.join(config.modRequest.platformProjectRoot, "app/src/main/res/xml");
        fs.mkdirSync(xmlDir, { recursive: true });
        fs.writeFileSync(
            path.join(xmlDir, "automotive_app_desc.xml"),
            '<?xml version="1.0" encoding="utf-8"?>\n<automotiveApp>\n    <uses name="media"/>\n</automotiveApp>\n',
            "utf8"
        );
        return config;
    }]);
}

// ── 4. Kotlin files ───────────────────────────────────────────────────────────
var PLAYBACK_SERVICE_KT = [
    "package com.nasosan.nasosanplayer",
    "",
    "import android.app.PendingIntent",
    "import android.appwidget.AppWidgetManager",
    "import android.content.Intent",
    "import androidx.annotation.OptIn",
    "import android.content.Context",
    "import android.net.Uri",
    "import android.os.Handler",
    "import android.os.Looper",
    "import androidx.media3.common.AudioAttributes",
    "import androidx.media3.common.C",
    "import androidx.media3.common.MediaItem",
    "import androidx.media3.common.MediaMetadata",
    "import androidx.media3.common.Player",
    "import androidx.media3.common.util.UnstableApi",
    "import androidx.media3.exoplayer.ExoPlayer",
    "import androidx.media3.session.LibraryResult",
    "import androidx.media3.session.MediaLibraryService",
    "import androidx.media3.session.MediaLibraryService.LibraryParams",
    "import androidx.media3.session.MediaLibraryService.MediaLibrarySession",
    "import androidx.media3.session.MediaSession",
    "import com.google.common.util.concurrent.Futures",
    "import com.google.common.util.concurrent.ListenableFuture",
    "",
    "@OptIn(UnstableApi::class)",
    "class NasoSanPlaybackService : MediaLibraryService() {",
    "",
    "    companion object {",
    "        @Volatile var instance: NasoSanPlaybackService? = null",
    "        private const val ROOT_ID = \"__nasosan_root__\"",
    "    }",
    "",
    "    private val mainHandler = Handler(Looper.getMainLooper())",
    "    lateinit var player: ExoPlayer",
    "    private lateinit var mediaSession: MediaLibrarySession",
    "",
    "    override fun onCreate() {",
    "        super.onCreate()",
    "        instance = this",
    "        player = ExoPlayer.Builder(this)",
    "            .setAudioAttributes(",
    "                AudioAttributes.Builder()",
    "                    .setContentType(C.AUDIO_CONTENT_TYPE_MUSIC)",
    "                    .setUsage(C.USAGE_MEDIA)",
    "                    .build(),",
    "                true",
    "            )",
    "            .build()",
    "        player.repeatMode = Player.REPEAT_MODE_OFF",
    "        loadPersistedTracks()",
    "        val launchIntent = packageManager.getLaunchIntentForPackage(packageName) ?: Intent()",
    "        val pi = PendingIntent.getActivity(",
    "            this, 0, launchIntent,",
    "            PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE",
    "        )",
    "        mediaSession = MediaLibrarySession.Builder(this, player, LibraryCallback())",
    "            .setSessionActivity(pi)",
    "            .build()",
    "    }",
    "",
    "    private fun isAndroidAutoController(pkg: String): Boolean =",
    "        pkg == \"com.google.android.projection.gearhead\" ||",
    "        pkg == \"com.android.car.media\" ||",
    "        pkg == \"com.google.android.carassistant\"",
    "",
    "    private fun loadPersistedTracks() {",
    "        try {",
    "            val json = getSharedPreferences(\"nasosan_prefs\", Context.MODE_PRIVATE)",
    "                .getString(\"track_queue_json\", null) ?: return",
    "            val arr = org.json.JSONArray(json)",
    "            val items = (0 until arr.length()).mapNotNull { i ->",
    "                val obj = arr.optJSONObject(i) ?: return@mapNotNull null",
    "                val url = obj.optString(\"url\", \"\")",
    "                if (url.isEmpty()) return@mapNotNull null",
    "                MediaItem.Builder()",
    "                    .setMediaId(obj.optString(\"id\", i.toString()))",
    "                    .setUri(Uri.parse(url))",
    "                    .setMediaMetadata(",
    "                        MediaMetadata.Builder()",
    "                            .setTitle(obj.optString(\"title\", \"\"))",
    "                            .setArtist(obj.optString(\"artist\", \"\"))",
    "                            .setIsBrowsable(false)",
    "                            .setIsPlayable(true)",
    "                            .build()",
    "                    )",
    "                    .build()",
    "            }",
    "            if (items.isNotEmpty()) {",
    "                player.setMediaItems(items)",
    "                player.prepare()",
    "            }",
    "        } catch (_: Exception) {}",
    "    }",
    "",
    "    override fun onGetSession(controllerInfo: MediaSession.ControllerInfo): MediaLibrarySession? = mediaSession",
    "",
    "    override fun onDestroy() {",
    "        instance = null",
    "        mainHandler.removeCallbacksAndMessages(null)",
    "        mediaSession.release()",
    "        player.release()",
    "        super.onDestroy()",
    "    }",
    "",
    "    inner class LibraryCallback : MediaLibrarySession.Callback {",
    "",
    "        override fun onConnect(",
    "            session: MediaSession,",
    "            controller: MediaSession.ControllerInfo",
    "        ): MediaSession.ConnectionResult {",
    "            val base = super.onConnect(session, controller)",
    "            val cmds = Player.Commands.Builder().addAllCommands().build()",
    "            if (isAndroidAutoController(controller.packageName) && player.mediaItemCount > 0) {",
    "                mainHandler.postDelayed({",
    "                    try {",
    "                        if (!player.isPlaying) {",
    "                            if (player.playbackState == Player.STATE_IDLE) player.prepare()",
    "                            player.play()",
    "                        }",
    "                    } catch (_: Exception) {}",
    "                }, 1000)",
    "            }",
    "            if (isAndroidAutoController(controller.packageName)) {",
    "                mainHandler.postDelayed({",
    "                    try {",
    "                        packageManager.getLaunchIntentForPackage(packageName)?.apply {",
    "                            flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_REORDER_TO_FRONT",
    "                        }?.let { startActivity(it) }",
    "                    } catch (_: Exception) {}",
    "                }, 1500)",
    "            }",
    "            return MediaSession.ConnectionResult.accept(base.availableSessionCommands, cmds)",
    "        }",
    "",
    "        override fun onDisconnected(",
    "            session: MediaSession,",
    "            controller: MediaSession.ControllerInfo",
    "        ) {",
    "            if (isAndroidAutoController(controller.packageName)) {",
    "                mainHandler.post { try { player.pause() } catch (_: Exception) {} }",
    "            }",
    "            super.onDisconnected(session, controller)",
    "        }",
    "",
    "        override fun onGetLibraryRoot(",
    "            session: MediaLibrarySession,",
    "            browser: MediaSession.ControllerInfo,",
    "            params: LibraryParams?",
    "        ): ListenableFuture<LibraryResult<MediaItem>> {",
    "            return Futures.immediateFuture(",
    "                LibraryResult.ofItem(",
    "                    MediaItem.Builder()",
    "                        .setMediaId(ROOT_ID)",
    "                        .setMediaMetadata(",
    "                            MediaMetadata.Builder()",
    "                                .setIsBrowsable(true)",
    "                                .setIsPlayable(false)",
    "                                .build()",
    "                        )",
    "                        .build(),",
    "                    params",
    "                )",
    "            )",
    "        }",
    "",
    "        override fun onGetChildren(",
    "            session: MediaLibrarySession,",
    "            browser: MediaSession.ControllerInfo,",
    "            parentId: String,",
    "            page: Int,",
    "            pageSize: Int,",
    "            params: LibraryParams?",
    "        ): ListenableFuture<LibraryResult<com.google.common.collect.ImmutableList<MediaItem>>> {",
    "            if (parentId != ROOT_ID) {",
    "                return Futures.immediateFuture(LibraryResult.ofItemList(emptyList(), params))",
    "            }",
    "            val items = NasoSanTrackCache.queue.mapIndexed { i, t ->",
    "                MediaItem.Builder()",
    "                    .setMediaId(i.toString())",
    "                    .setMediaMetadata(",
    "                        MediaMetadata.Builder()",
    "                            .setTitle(t.first)",
    "                            .setArtist(t.second)",
    "                            .setIsBrowsable(false)",
    "                            .setIsPlayable(true)",
    "                            .build()",
    "                    )",
    "                    .build()",
    "            }",
    "            return Futures.immediateFuture(LibraryResult.ofItemList(items, params))",
    "        }",
    "",
    "        override fun onSetMediaItems(",
    "            mediaSession: MediaSession,",
    "            controller: MediaSession.ControllerInfo,",
    "            mediaItems: MutableList<MediaItem>,",
    "            startIndex: Int,",
    "            startPositionMs: Long",
    "        ): ListenableFuture<MediaSession.MediaItemsWithStartPosition> {",
    "            if (mediaItems.size == 1) {",
    "                val reqId = mediaItems[0].mediaId",
    "                val idx = (0 until player.mediaItemCount).firstOrNull {",
    "                    player.getMediaItemAt(it).mediaId == reqId",
    "                }",
    "                if (idx != null) {",
    "                    return Futures.immediateFuture(",
    "                        MediaSession.MediaItemsWithStartPosition(",
    "                            (0 until player.mediaItemCount).map { player.getMediaItemAt(it) },",
    "                            idx, 0L",
    "                        )",
    "                    )",
    "                }",
    "            }",
    "            return super.onSetMediaItems(mediaSession, controller, mediaItems, startIndex, startPositionMs)",
    "        }",
    "    }",
    "}",
    "",
].join("\n");

var PLAYER_MODULE_KT = [
    "package com.nasosan.nasosanplayer",
    "",
    "import android.content.Intent",
    "import android.net.Uri",
    "import android.os.Handler",
    "import android.os.Looper",
    "import androidx.annotation.OptIn",
    "import androidx.media3.common.MediaItem",
    "import androidx.media3.common.MediaMetadata",
    "import androidx.media3.common.PlaybackException",
    "import androidx.media3.common.Player",
    "import androidx.media3.common.util.UnstableApi",
    "import androidx.media3.exoplayer.ExoPlayer",
    "import com.facebook.react.bridge.*",
    "import com.facebook.react.modules.core.DeviceEventManagerModule",
    "",
    "@OptIn(UnstableApi::class)",
    "class NasoSanPlayerModule(private val ctx: ReactApplicationContext) : ReactContextBaseJavaModule(ctx) {",
    "",
    "    private val mainHandler = Handler(Looper.getMainLooper())",
    "    private var listenedPlayer: ExoPlayer? = null",
    "",
    "    override fun getName() = \"NasoSanPlayer\"",
    "",
    "    private fun getPlayer(): ExoPlayer? = NasoSanPlaybackService.instance?.player",
    "",
    "    private fun send(event: String, data: WritableMap?) {",
    "        try {",
    "            ctx.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter::class.java)",
    "                ?.emit(event, data)",
    "        } catch (_: Exception) {}",
    "    }",
    "",
    "    private val playerListener = object : Player.Listener {",
    "        override fun onMediaItemTransition(mediaItem: MediaItem?, reason: Int) {",
    "            val player = getPlayer() ?: return",
    "            val map = Arguments.createMap()",
    "            map.putInt(\"index\", player.currentMediaItemIndex)",
    "            map.putInt(\"reason\", reason)",
    "            if (mediaItem != null) {",
    "                val t = Arguments.createMap()",
    "                t.putString(\"id\", mediaItem.mediaId)",
    "                t.putString(\"title\", mediaItem.mediaMetadata.title?.toString() ?: \"\")",
    "                t.putString(\"artist\", mediaItem.mediaMetadata.artist?.toString() ?: \"\")",
    "                t.putString(\"url\", mediaItem.localConfiguration?.uri?.toString() ?: \"\")",
    "                map.putMap(\"track\", t)",
    "            }",
    "            send(\"nasosan-active-track-changed\", map)",
    "        }",
    "        override fun onIsPlayingChanged(isPlaying: Boolean) {",
    "            val player = getPlayer() ?: return",
    "            val map = Arguments.createMap()",
    "            val s = when {",
    "                isPlaying -> \"playing\"",
    "                player.playbackState == Player.STATE_IDLE -> \"none\"",
    "                player.playbackState == Player.STATE_ENDED -> \"stopped\"",
    "                else -> \"paused\"",
    "            }",
    "            map.putString(\"state\", s)",
    "            send(\"nasosan-playback-state\", map)",
    "        }",
    "        override fun onPlaybackStateChanged(playbackState: Int) {",
    "            if (playbackState == Player.STATE_ENDED) {",
    "                send(\"nasosan-queue-ended\", null)",
    "            }",
    "        }",
    "        override fun onPlayerError(error: PlaybackException) {",
    "            val map = Arguments.createMap()",
    "            map.putString(\"message\", error.message ?: \"Playback error\")",
    "            send(\"nasosan-playback-error\", map)",
    "        }",
    "    }",
    "",
    "    private fun ensureListeners() {",
    "        val player = getPlayer() ?: return",
    "        if (listenedPlayer === player) return",
    "        listenedPlayer?.removeListener(playerListener)",
    "        player.addListener(playerListener)",
    "        listenedPlayer = player",
    "    }",
    "",
    "    private fun pollForService(promise: Promise, attempt: Int) {",
    "        mainHandler.postDelayed({",
    "            val svc = NasoSanPlaybackService.instance",
    "            if (svc != null) {",
    "                ensureListeners()",
    "                promise.resolve(null)",
    "            } else if (attempt < 50) {",
    "                pollForService(promise, attempt + 1)",
    "            } else {",
    "                promise.reject(\"TIMEOUT\", \"Playback service not ready\")",
    "            }",
    "        }, 300)",
    "    }",
    "",
    "    @ReactMethod",
    "    fun setup(options: ReadableMap?, promise: Promise) {",
    "        if (NasoSanPlaybackService.instance != null) {",
    "            mainHandler.post { ensureListeners() }",
    "            promise.resolve(null)",
    "            return",
    "        }",
    "        mainHandler.post {",
    "            try { ctx.startService(Intent(ctx, NasoSanPlaybackService::class.java)) } catch (_: Exception) {}",
    "        }",
    "        pollForService(promise, 0)",
    "    }",
    "",
    "    @ReactMethod",
    "    fun updateOptions(options: ReadableMap?, promise: Promise) { promise.resolve(null) }",
    "",
    "    @ReactMethod",
    "    fun reset(promise: Promise) {",
    "        mainHandler.post {",
    "            try {",
    "                getPlayer()?.let { it.stop(); it.clearMediaItems() }",
    "                promise.resolve(null)",
    "            } catch (e: Exception) { promise.reject(\"ERROR\", e.message) }",
    "        }",
    "    }",
    "",
    "    @ReactMethod",
    "    fun add(tracksArr: ReadableArray, promise: Promise) {",
    "        val player = getPlayer() ?: return promise.reject(\"NOT_READY\", \"Call setup() first\")",
    "        mainHandler.post {",
    "            try {",
    "                val items = (0 until tracksArr.size()).mapNotNull { i ->",
    "                    val t = tracksArr.getMap(i) ?: return@mapNotNull null",
    "                    val url = t.getString(\"url\") ?: return@mapNotNull null",
    "                    val meta = MediaMetadata.Builder()",
    "                        .setTitle(t.getString(\"title\"))",
    "                        .setArtist(t.getString(\"artist\"))",
    "                        .setAlbumTitle(t.getString(\"album\") ?: \"\")",
    "                    val artwork = t.getString(\"artwork\")",
    "                    if (artwork != null) {",
    "                        try { meta.setArtworkUri(Uri.parse(artwork)) } catch (_: Exception) {}",
    "                    }",
    "                    MediaItem.Builder()",
    "                        .setMediaId(t.getString(\"id\") ?: i.toString())",
    "                        .setUri(url)",
    "                        .setMediaMetadata(meta.build())",
    "                        .build()",
    "                }",
    "                player.addMediaItems(items)",
    "                if (player.playbackState == Player.STATE_IDLE) player.prepare()",
    "                promise.resolve(null)",
    "            } catch (e: Exception) { promise.reject(\"ERROR\", e.message) }",
    "        }",
    "    }",
    "",
    "    @ReactMethod",
    "    fun play(promise: Promise) {",
    "        mainHandler.post {",
    "            try {",
    "                getPlayer()?.let {",
    "                    if (it.playbackState == Player.STATE_IDLE) it.prepare()",
    "                    if (it.playbackState == Player.STATE_ENDED) it.seekTo(0, 0)",
    "                    it.play()",
    "                }",
    "                promise.resolve(null)",
    "            } catch (e: Exception) { promise.reject(\"ERROR\", e.message) }",
    "        }",
    "    }",
    "",
    "    @ReactMethod",
    "    fun pause(promise: Promise) {",
    "        mainHandler.post {",
    "            try { getPlayer()?.pause(); promise.resolve(null) }",
    "            catch (e: Exception) { promise.reject(\"ERROR\", e.message) }",
    "        }",
    "    }",
    "",
    "    @ReactMethod",
    "    fun stop(promise: Promise) {",
    "        mainHandler.post {",
    "            try { getPlayer()?.stop(); promise.resolve(null) }",
    "            catch (e: Exception) { promise.reject(\"ERROR\", e.message) }",
    "        }",
    "    }",
    "",
    "    @ReactMethod",
    "    fun skip(index: Int, promise: Promise) {",
    "        mainHandler.post {",
    "            try {",
    "                getPlayer()?.let {",
    "                    it.seekToDefaultPosition(index)",
    "                    if (it.playbackState == Player.STATE_IDLE) it.prepare()",
    "                }",
    "                promise.resolve(null)",
    "            } catch (e: Exception) { promise.reject(\"ERROR\", e.message) }",
    "        }",
    "    }",
    "",
    "    @ReactMethod",
    "    fun skipToNext(promise: Promise) {",
    "        mainHandler.post {",
    "            try { getPlayer()?.seekToNextMediaItem(); promise.resolve(null) }",
    "            catch (e: Exception) { promise.reject(\"ERROR\", e.message) }",
    "        }",
    "    }",
    "",
    "    @ReactMethod",
    "    fun skipToPrevious(promise: Promise) {",
    "        mainHandler.post {",
    "            try { getPlayer()?.seekToPreviousMediaItem(); promise.resolve(null) }",
    "            catch (e: Exception) { promise.reject(\"ERROR\", e.message) }",
    "        }",
    "    }",
    "",
    "    @ReactMethod",
    "    fun shutdown(promise: Promise) {",
    "        mainHandler.post {",
    "            try {",
    "                NasoSanPlaybackService.instance?.let { svc ->",
    "                    svc.player.stop()",
    "                    svc.player.clearMediaItems()",
    "                    svc.stopSelf()",
    "                }",
    "                promise.resolve(null)",
    "            } catch (e: Exception) { promise.reject(\"ERROR\", e.message) }",
    "        }",
    "    }",
    "",
    "    @ReactMethod",
    "    fun seekTo(seconds: Double, promise: Promise) {",
    "        mainHandler.post {",
    "            try { getPlayer()?.seekTo((seconds * 1000).toLong()); promise.resolve(null) }",
    "            catch (e: Exception) { promise.reject(\"ERROR\", e.message) }",
    "        }",
    "    }",
    "",
    "    @ReactMethod",
    "    fun getPosition(promise: Promise) {",
    "        mainHandler.post {",
    "            try { promise.resolve((getPlayer()?.currentPosition ?: 0L) / 1000.0) }",
    "            catch (_: Exception) { promise.resolve(0.0) }",
    "        }",
    "    }",
    "",
    "    @ReactMethod",
    "    fun getDuration(promise: Promise) {",
    "        mainHandler.post {",
    "            try {",
    "                val dur = getPlayer()?.duration ?: 0L",
    "                promise.resolve(if (dur < 0) 0.0 else dur / 1000.0)",
    "            } catch (_: Exception) { promise.resolve(0.0) }",
    "        }",
    "    }",
    "",
    "    @ReactMethod",
    "    fun getQueue(promise: Promise) {",
    "        mainHandler.post {",
    "            try {",
    "                val arr = Arguments.createArray()",
    "                val player = getPlayer()",
    "                if (player != null) {",
    "                    for (i in 0 until player.mediaItemCount) {",
    "                        val item = player.getMediaItemAt(i)",
    "                        val map = Arguments.createMap()",
    "                        map.putString(\"id\", item.mediaId)",
    "                        map.putString(\"url\", item.localConfiguration?.uri?.toString() ?: \"\")",
    "                        map.putString(\"title\", item.mediaMetadata.title?.toString() ?: \"\")",
    "                        map.putString(\"artist\", item.mediaMetadata.artist?.toString() ?: \"\")",
    "                        arr.pushMap(map)",
    "                    }",
    "                }",
    "                promise.resolve(arr)",
    "            } catch (e: Exception) { promise.reject(\"ERROR\", e.message) }",
    "        }",
    "    }",
    "",
    "    @ReactMethod",
    "    fun updateMetadataForTrack(index: Int, metadata: ReadableMap, promise: Promise) {",
    "        mainHandler.post {",
    "            try {",
    "                val player = getPlayer() ?: return@post promise.resolve(null)",
    "                if (index < 0 || index >= player.mediaItemCount) return@post promise.resolve(null)",
    "                val old = player.getMediaItemAt(index)",
    "                val newMeta = MediaMetadata.Builder()",
    "                    .setTitle(metadata.getString(\"title\") ?: old.mediaMetadata.title)",
    "                    .setArtist(metadata.getString(\"artist\") ?: old.mediaMetadata.artist)",
    "                    .build()",
    "                player.replaceMediaItem(index, old.buildUpon().setMediaMetadata(newMeta).build())",
    "                promise.resolve(null)",
    "            } catch (e: Exception) { promise.reject(\"ERROR\", e.message) }",
    "        }",
    "    }",
    "",
    "    @ReactMethod",
    "    fun getPlaybackState(promise: Promise) {",
    "        mainHandler.post {",
    "            try {",
    "                val player = getPlayer()",
    "                val s = when {",
    "                    player == null -> \"none\"",
    "                    player.isPlaying -> \"playing\"",
    "                    player.playbackState == Player.STATE_IDLE -> \"none\"",
    "                    player.playbackState == Player.STATE_ENDED -> \"stopped\"",
    "                    else -> \"paused\"",
    "                }",
    "                promise.resolve(s)",
    "            } catch (_: Exception) { promise.resolve(\"none\") }",
    "        }",
    "    }",
    "",
    "    @ReactMethod fun addListener(eventName: String) {}",
    "    @ReactMethod fun removeListeners(count: Int) {}",
    "}",
    "",
].join("\n");

var PLAYER_PACKAGE_KT = [
    "package com.nasosan.nasosanplayer",
    "",
    "import com.facebook.react.ReactPackage",
    "import com.facebook.react.bridge.NativeModule",
    "import com.facebook.react.bridge.ReactApplicationContext",
    "import com.facebook.react.uimanager.ViewManager",
    "",
    "class NasoSanPlayerPackage : ReactPackage {",
    "    override fun createNativeModules(ctx: ReactApplicationContext): List<NativeModule> =",
    "        listOf(NasoSanPlayerModule(ctx))",
    "    override fun createViewManagers(ctx: ReactApplicationContext): List<ViewManager<*, *>> =",
    "        emptyList()",
    "}",
    "",
].join("\n");

var NASOSAN_TRACK_CACHE_KT = [
    "package com.nasosan.nasosanplayer",
    "",
    "object NasoSanTrackCache {",
    "    @Volatile var currentTitle: String? = null",
    "    @Volatile var currentArtist: String? = null",
    "    @Volatile var queue: List<Pair<String, String>> = emptyList()",
    "}",
    "",
].join("\n");

var TRACK_CACHE_MODULE_KT = [
    "package com.nasosan.nasosanplayer",
    "",
    "import android.content.Context",
    "import com.facebook.react.bridge.ReactApplicationContext",
    "import com.facebook.react.bridge.ReactContextBaseJavaModule",
    "import com.facebook.react.bridge.ReactMethod",
    "",
    "class TrackCacheModule(private val ctx: ReactApplicationContext) : ReactContextBaseJavaModule(ctx) {",
    "    override fun getName() = \"TrackCache\"",
    "",
    "    @ReactMethod",
    "    fun update(title: String, artist: String, queueJson: String) {",
    "        NasoSanTrackCache.currentTitle = title",
    "        NasoSanTrackCache.currentArtist = artist",
    "        try {",
    "            val arr = org.json.JSONArray(queueJson)",
    "            val list = mutableListOf<Pair<String, String>>()",
    "            for (i in 0 until arr.length()) {",
    "                val obj = arr.getJSONObject(i)",
    "                list.add(Pair(obj.optString(\"title\", \"\"), obj.optString(\"artist\", \"\")))",
    "            }",
    "            NasoSanTrackCache.queue = list",
    "        } catch (_: Exception) {}",
    "        try {",
    "            ctx.getSharedPreferences(\"nasosan_prefs\", Context.MODE_PRIVATE)",
    "                .edit().putString(\"track_queue_json\", queueJson).apply()",
    "        } catch (_: Exception) {}",
    "    }",
    "}",
    "",
].join("\n");

var TRACK_CACHE_PACKAGE_KT = [
    "package com.nasosan.nasosanplayer",
    "",
    "import com.facebook.react.ReactPackage",
    "import com.facebook.react.bridge.NativeModule",
    "import com.facebook.react.bridge.ReactApplicationContext",
    "import com.facebook.react.uimanager.ViewManager",
    "",
    "class TrackCachePackage : ReactPackage {",
    "    override fun createNativeModules(ctx: ReactApplicationContext): List<NativeModule> =",
    "        listOf(TrackCacheModule(ctx))",
    "    override fun createViewManagers(ctx: ReactApplicationContext): List<ViewManager<*, *>> =",
    "        emptyList()",
    "}",
    "",
].join("\n");

var CAR_MODE_MODULE_KT = [
    "package com.nasosan.nasosanplayer",
    "",
    "import android.content.Context",
    "import android.media.AudioDeviceCallback",
    "import android.media.AudioDeviceInfo",
    "import android.media.AudioManager",
    "import android.os.Handler",
    "import android.os.Looper",
    "import com.facebook.react.bridge.Promise",
    "import com.facebook.react.bridge.ReactApplicationContext",
    "import com.facebook.react.bridge.ReactContextBaseJavaModule",
    "import com.facebook.react.bridge.ReactMethod",
    "import com.facebook.react.modules.core.DeviceEventManagerModule",
    "",
    "class CarModeModule(private val ctx: ReactApplicationContext) : ReactContextBaseJavaModule(ctx) {",
    "",
    "    override fun getName() = \"CarModeModule\"",
    "",
    "    private val audioManager = ctx.getSystemService(Context.AUDIO_SERVICE) as AudioManager",
    "    private val mainHandler = Handler(Looper.getMainLooper())",
    "",
    "    private fun isUsbAudio(d: AudioDeviceInfo): Boolean =",
    "        d.type == AudioDeviceInfo.TYPE_USB_DEVICE ||",
    "        d.type == AudioDeviceInfo.TYPE_USB_ACCESSORY ||",
    "        d.type == AudioDeviceInfo.TYPE_USB_HEADSET",
    "",
    "    private fun hasUsbAudioOutput(): Boolean =",
    "        audioManager.getDevices(AudioManager.GET_DEVICES_OUTPUTS).any { isUsbAudio(it) }",
    "",
    "    private val audioDeviceCallback = object : AudioDeviceCallback() {",
    "        override fun onAudioDevicesAdded(added: Array<AudioDeviceInfo>) {",
    "            if (added.none { isUsbAudio(it) }) return",
    "            ctx.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter::class.java)",
    "                ?.emit(\"nasosan_car_enter\", null)",
    "        }",
    "        override fun onAudioDevicesRemoved(removed: Array<AudioDeviceInfo>) {",
    "            if (removed.none { isUsbAudio(it) }) return",
    "            try { NasoSanPlaybackService.instance?.player?.pause() } catch (_: Exception) {}",
    "            ctx.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter::class.java)",
    "                ?.emit(\"nasosan_car_exit\", null)",
    "        }",
    "    }",
    "",
    "    private var listening = false",
    "",
    "    @ReactMethod",
    "    fun startListening() {",
    "        if (listening) return",
    "        audioManager.registerAudioDeviceCallback(audioDeviceCallback, mainHandler)",
    "        listening = true",
    "    }",
    "",
    "    @ReactMethod",
    "    fun stopListening() {",
    "        if (!listening) return",
    "        try { audioManager.unregisterAudioDeviceCallback(audioDeviceCallback) } catch (_: Exception) {}",
    "        listening = false",
    "    }",
    "",
    "    @ReactMethod",
    "    fun isInCarMode(promise: Promise) {",
    "        promise.resolve(hasUsbAudioOutput())",
    "    }",
    "",
    "    @ReactMethod fun addListener(eventName: String) {}",
    "    @ReactMethod fun removeListeners(count: Int) {}",
    "}",
    "",
].join("\n");

var CAR_MODE_PACKAGE_KT = [
    "package com.nasosan.nasosanplayer",
    "",
    "import com.facebook.react.ReactPackage",
    "import com.facebook.react.bridge.NativeModule",
    "import com.facebook.react.bridge.ReactApplicationContext",
    "import com.facebook.react.uimanager.ViewManager",
    "",
    "class CarModePackage : ReactPackage {",
    "    override fun createNativeModules(ctx: ReactApplicationContext): List<NativeModule> =",
    "        listOf(CarModeModule(ctx))",
    "    override fun createViewManagers(ctx: ReactApplicationContext): List<ViewManager<*, *>> =",
    "        emptyList()",
    "}",
    "",
].join("\n");

var SPEECHNOTES_WIDGET_MODULE_KT = [
    "package com.nasosan.nasosanplayer",
    "",
    "import android.appwidget.AppWidgetHost",
    "import android.appwidget.AppWidgetManager",
    "import android.content.Context",
    "import android.content.Intent",
    "import android.content.pm.PackageManager",
    "import android.net.Uri",
    "import com.facebook.react.bridge.ActivityEventListener",
    "import com.facebook.react.bridge.Promise",
    "import com.facebook.react.bridge.ReactApplicationContext",
    "import com.facebook.react.bridge.ReactContextBaseJavaModule",
    "import com.facebook.react.bridge.ReactMethod",
    "",
    "class SpeechnotesWidgetModule(private val ctx: ReactApplicationContext)",
    "    : ReactContextBaseJavaModule(ctx), ActivityEventListener {",
    "",
    "    companion object {",
    "        const val PKG = \"co.speechnotes.speechnotes\"",
    "        const val HOST_ID = 2001",
    "        const val PREFS_WIDGET_ID = \"speechnotes_widget_id\"",
    "        const val REQ_BIND = 9877",
    "    }",
    "",
    "    private var bindPromise: Promise? = null",
    "    private var pendingId = AppWidgetManager.INVALID_APPWIDGET_ID",
    "",
    "    init { ctx.addActivityEventListener(this) }",
    "",
    "    override fun getName() = \"SpeechnotesWidgetModule\"",
    "",
    "    @ReactMethod",
    "    fun isInstalled(promise: Promise) {",
    "        try {",
    "            ctx.packageManager.getPackageInfo(PKG, 0)",
    "            promise.resolve(true)",
    "        } catch (_: PackageManager.NameNotFoundException) {",
    "            promise.resolve(false)",
    "        }",
    "    }",
    "",
    "    @ReactMethod",
    "    fun openPlayStore() {",
    "        try {",
    "            ctx.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(\"market://details?id=$PKG\"))",
    "                .apply { flags = Intent.FLAG_ACTIVITY_NEW_TASK })",
    "        } catch (_: Exception) {",
    "            try {",
    "                ctx.startActivity(Intent(Intent.ACTION_VIEW,",
    "                    Uri.parse(\"https://play.google.com/store/apps/details?id=$PKG\"))",
    "                    .apply { flags = Intent.FLAG_ACTIVITY_NEW_TASK })",
    "            } catch (_: Exception) {}",
    "        }",
    "    }",
    "",
    "    @ReactMethod",
    "    fun getWidgetId(promise: Promise) {",
    "        val id = ctx.getSharedPreferences(\"nasosan_prefs\", Context.MODE_PRIVATE)",
    "            .getInt(PREFS_WIDGET_ID, AppWidgetManager.INVALID_APPWIDGET_ID)",
    "        promise.resolve(if (id == AppWidgetManager.INVALID_APPWIDGET_ID) -1 else id)",
    "    }",
    "",
    "    @ReactMethod",
    "    fun requestBind(promise: Promise) {",
    "        try {",
    "            val prefs = ctx.getSharedPreferences(\"nasosan_prefs\", Context.MODE_PRIVATE)",
    "            val existing = prefs.getInt(PREFS_WIDGET_ID, AppWidgetManager.INVALID_APPWIDGET_ID)",
    "            if (existing != AppWidgetManager.INVALID_APPWIDGET_ID) { promise.resolve(existing); return }",
    "            val awm = AppWidgetManager.getInstance(ctx)",
    "            val allProviders = awm.getInstalledProviders().filter { it.provider.packageName == PKG }",
    "            val provider = allProviders.minByOrNull { it.minWidth * it.minHeight }",
    "                ?: allProviders.firstOrNull()",
    "                ?: return promise.reject(\"NO_PROVIDER\", \"Widget Speechnotes non trovato\")",
    "            val host = AppWidgetHost(ctx.applicationContext, HOST_ID)",
    "            val wid = host.allocateAppWidgetId()",
    "            if (awm.bindAppWidgetIdIfAllowed(wid, provider.provider)) {",
    "                prefs.edit().putInt(PREFS_WIDGET_ID, wid).apply()",
    "                promise.resolve(wid)",
    "                return",
    "            }",
    "            val act = ctx.currentActivity ?: return promise.reject(\"NO_ACTIVITY\", \"Nessuna activity\")",
    "            bindPromise = promise",
    "            pendingId = wid",
    "            act.startActivityForResult(",
    "                Intent(AppWidgetManager.ACTION_APPWIDGET_BIND).apply {",
    "                    putExtra(AppWidgetManager.EXTRA_APPWIDGET_ID, wid)",
    "                    putExtra(AppWidgetManager.EXTRA_APPWIDGET_PROVIDER, provider.provider)",
    "                },",
    "                REQ_BIND",
    "            )",
    "        } catch (e: Exception) { promise.reject(\"ERROR\", e.message) }",
    "    }",
    "",
    "    @ReactMethod",
    "    fun unbind() {",
    "        val prefs = ctx.getSharedPreferences(\"nasosan_prefs\", Context.MODE_PRIVATE)",
    "        val wid = prefs.getInt(PREFS_WIDGET_ID, AppWidgetManager.INVALID_APPWIDGET_ID)",
    "        if (wid != AppWidgetManager.INVALID_APPWIDGET_ID) {",
    "            try { AppWidgetHost(ctx.applicationContext, HOST_ID).deleteAppWidgetId(wid) } catch (_: Exception) {}",
    "            prefs.edit().remove(PREFS_WIDGET_ID).apply()",
    "        }",
    "    }",
    "",
    "    override fun onActivityResult(act: android.app.Activity, req: Int, res: Int, data: android.content.Intent?) {",
    "        if (req != REQ_BIND) return",
    "        val p = bindPromise ?: return",
    "        bindPromise = null",
    "        if (res == android.app.Activity.RESULT_OK) {",
    "            ctx.getSharedPreferences(\"nasosan_prefs\", Context.MODE_PRIVATE)",
    "                .edit().putInt(PREFS_WIDGET_ID, pendingId).apply()",
    "            p.resolve(pendingId)",
    "        } else {",
    "            try { AppWidgetHost(ctx.applicationContext, HOST_ID).deleteAppWidgetId(pendingId) } catch (_: Exception) {}",
    "            p.reject(\"DENIED\", \"Binding negato\")",
    "        }",
    "        pendingId = AppWidgetManager.INVALID_APPWIDGET_ID",
    "    }",
    "",
    "    override fun onNewIntent(intent: android.content.Intent) {}",
    "",
    "    @ReactMethod fun addListener(e: String) {}",
    "    @ReactMethod fun removeListeners(c: Int) {}",
    "}",
    "",
].join("\n");

var SPEECHNOTES_WIDGET_VIEW_MANAGER_KT = [
    "package com.nasosan.nasosanplayer",
    "",
    "import android.appwidget.AppWidgetHost",
    "import android.appwidget.AppWidgetManager",
    "import android.content.Context",
    "import android.view.MotionEvent",
    "import android.widget.FrameLayout",
    "import com.facebook.react.bridge.Arguments",
    "import com.facebook.react.bridge.ReactApplicationContext",
    "import com.facebook.react.uimanager.SimpleViewManager",
    "import com.facebook.react.uimanager.ThemedReactContext",
    "import com.facebook.react.uimanager.events.RCTEventEmitter",
    "",
    "class SpeechnotesWidgetViewManager(private val ctx: ReactApplicationContext) : SimpleViewManager<FrameLayout>() {",
    "",
    "    companion object {",
    "        const val REACT_CLASS = \"SpeechnotesWidgetView\"",
    "        const val PKG = \"co.speechnotes.speechnotes\"",
    "        const val HOST_ID = 2001",
    "        const val PREFS_WIDGET_ID = \"speechnotes_widget_id\"",
    "    }",
    "",
    "    private val host: AppWidgetHost by lazy { AppWidgetHost(ctx.applicationContext, HOST_ID) }",
    "",
    "    override fun getName() = REACT_CLASS",
    "",
    "    override fun createViewInstance(context: ThemedReactContext): FrameLayout {",
    "        return object : FrameLayout(context) {",
    "            override fun onInterceptTouchEvent(ev: MotionEvent): Boolean {",
    "                if (ev.action == MotionEvent.ACTION_DOWN) {",
    "                    context.getJSModule(RCTEventEmitter::class.java)",
    "                        ?.receiveEvent(id, \"onWidgetTap\", Arguments.createMap())",
    "                }",
    "                return false",
    "            }",
    "        }",
    "    }",
    "",
    "    @Suppress(\"UNCHECKED_CAST\")",
    "    override fun getExportedCustomBubblingEventTypeConstants(): Map<String, Any> = mapOf(",
    "        \"onWidgetTap\" to mapOf(",
    "            \"phasedRegistrationNames\" to mapOf(",
    "                \"bubbled\" to \"onWidgetTap\",",
    "                \"captured\" to \"onWidgetTapCapture\"",
    "            )",
    "        ),",
    "        \"onWidgetError\" to mapOf(",
    "            \"phasedRegistrationNames\" to mapOf(",
    "                \"bubbled\" to \"onWidgetError\",",
    "                \"captured\" to \"onWidgetErrorCapture\"",
    "            )",
    "        )",
    "    )",
    "",
    "    override fun onAfterUpdateTransaction(view: FrameLayout) {",
    "        super.onAfterUpdateTransaction(view)",
    "        if (view.childCount > 0) return",
    "        try {",
    "            val prefs = ctx.getSharedPreferences(\"nasosan_prefs\", Context.MODE_PRIVATE)",
    "            val wid = prefs.getInt(PREFS_WIDGET_ID, AppWidgetManager.INVALID_APPWIDGET_ID)",
    "            if (wid == AppWidgetManager.INVALID_APPWIDGET_ID) return",
    "            val awm = AppWidgetManager.getInstance(ctx)",
    "            val allProviders = awm.getInstalledProviders().filter { it.provider.packageName == PKG }",
    "            val provider = (allProviders.minByOrNull { it.minWidth * it.minHeight }",
    "                ?: allProviders.firstOrNull()) ?: return",
    "            host.startListening()",
    "            val hv = host.createView(ctx.applicationContext, wid, provider)",
    "            hv.setAppWidget(wid, provider)",
    "            view.addView(hv, FrameLayout.LayoutParams(",
    "                FrameLayout.LayoutParams.MATCH_PARENT,",
    "                FrameLayout.LayoutParams.MATCH_PARENT",
    "            ))",
    "        } catch (e: Exception) {",
    "            try {",
    "                val map = Arguments.createMap()",
    "                map.putString(\"error\", e.message ?: \"Unknown\")",
    "                (view.context as? ThemedReactContext)",
    "                    ?.getJSModule(RCTEventEmitter::class.java)",
    "                    ?.receiveEvent(view.id, \"onWidgetError\", map)",
    "            } catch (_: Exception) {}",
    "        }",
    "    }",
    "}",
    "",
].join("\n");

var SPEECHNOTES_WIDGET_PACKAGE_KT = [
    "package com.nasosan.nasosanplayer",
    "",
    "import com.facebook.react.ReactPackage",
    "import com.facebook.react.bridge.NativeModule",
    "import com.facebook.react.bridge.ReactApplicationContext",
    "import com.facebook.react.uimanager.ViewManager",
    "",
    "class SpeechnotesWidgetPackage : ReactPackage {",
    "    override fun createNativeModules(ctx: ReactApplicationContext): List<NativeModule> =",
    "        listOf(SpeechnotesWidgetModule(ctx))",
    "    override fun createViewManagers(ctx: ReactApplicationContext): List<ViewManager<*, *>> =",
    "        listOf(SpeechnotesWidgetViewManager(ctx))",
    "}",
    "",
].join("\n");

var WMA_MODULE_KT = [
    "package com.nasosan.nasosanplayer",
    "",
    "import android.media.MediaCodec",
    "import android.media.MediaExtractor",
    "import android.media.MediaFormat",
    "import android.net.Uri",
    "import com.facebook.react.bridge.Promise",
    "import com.facebook.react.bridge.ReactApplicationContext",
    "import com.facebook.react.bridge.ReactContextBaseJavaModule",
    "import com.facebook.react.bridge.ReactMethod",
    "import java.io.File",
    "import java.io.FileInputStream",
    "import java.io.FileOutputStream",
    "import java.nio.ByteBuffer",
    "import java.nio.ByteOrder",
    "",
    "class WmaPlayerModule(private val ctx: ReactApplicationContext) : ReactContextBaseJavaModule(ctx) {",
    "    override fun getName() = \"WmaPlayer\"",
    "",
    "    @ReactMethod",
    "    fun convertToWav(uri: String, outputPath: String, promise: Promise) {",
    "        Thread {",
    "            val outFile = if (outputPath.startsWith(\"file://\")) File(Uri.parse(outputPath).path!!) else File(outputPath)",
    "            val tmpFile = File(ctx.cacheDir, \"wma_pcm_${System.currentTimeMillis()}.tmp\")",
    "            var extractor: MediaExtractor? = null",
    "            var codec: MediaCodec? = null",
    "            try {",
    "                extractor = MediaExtractor()",
    "                extractor.setDataSource(ctx, Uri.parse(uri), null)",
    "                val trackIdx = (0 until extractor.trackCount).firstOrNull {",
    "                    extractor.getTrackFormat(it).getString(MediaFormat.KEY_MIME)?.startsWith(\"audio/\") == true",
    "                } ?: throw Exception(\"No audio track found in: $uri\")",
    "                extractor.selectTrack(trackIdx)",
    "                val format = extractor.getTrackFormat(trackIdx)",
    "                val mime = format.getString(MediaFormat.KEY_MIME)!!",
    "                val sampleRate = try { format.getInteger(MediaFormat.KEY_SAMPLE_RATE) } catch (_: Exception) { 44100 }",
    "                val channels = try { format.getInteger(MediaFormat.KEY_CHANNEL_COUNT) } catch (_: Exception) { 2 }",
    "                codec = MediaCodec.createDecoderByType(mime)",
    "                codec.configure(format, null, null, 0)",
    "                codec.start()",
    "                outFile.parentFile?.mkdirs()",
    "                tmpFile.delete()",
    "                var pcmSize = 0L",
    "                val info = MediaCodec.BufferInfo()",
    "                var inputDone = false",
    "                var outputDone = false",
    "                FileOutputStream(tmpFile).use { tmpOut ->",
    "                    while (!outputDone) {",
    "                        if (!inputDone) {",
    "                            val idx = codec.dequeueInputBuffer(5000)",
    "                            if (idx >= 0) {",
    "                                val buf = codec.getInputBuffer(idx)!!",
    "                                val sz = extractor.readSampleData(buf, 0)",
    "                                if (sz < 0) {",
    "                                    codec.queueInputBuffer(idx, 0, 0, 0, MediaCodec.BUFFER_FLAG_END_OF_STREAM)",
    "                                    inputDone = true",
    "                                } else {",
    "                                    codec.queueInputBuffer(idx, 0, sz, extractor.sampleTime, 0)",
    "                                    extractor.advance()",
    "                                }",
    "                            }",
    "                        }",
    "                        val outIdx = codec.dequeueOutputBuffer(info, 5000)",
    "                        if (outIdx >= 0) {",
    "                            if (info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM != 0) outputDone = true",
    "                            if (info.size > 0) {",
    "                                val buf = codec.getOutputBuffer(outIdx)!!",
    "                                val bytes = ByteArray(info.size)",
    "                                buf.get(bytes)",
    "                                tmpOut.write(bytes)",
    "                                pcmSize += info.size",
    "                            }",
    "                            codec.releaseOutputBuffer(outIdx, false)",
    "                        }",
    "                    }",
    "                }",
    "                val bitsPerSample = 16",
    "                val byteRate = sampleRate * channels * bitsPerSample / 8",
    "                outFile.delete()",
    "                FileOutputStream(outFile).use { out ->",
    "                    val header = ByteBuffer.allocate(44).order(ByteOrder.LITTLE_ENDIAN)",
    "                    header.put(\"RIFF\".toByteArray())",
    "                    header.putInt((36 + pcmSize).toInt())",
    "                    header.put(\"WAVE\".toByteArray())",
    "                    header.put(\"fmt \".toByteArray())",
    "                    header.putInt(16)",
    "                    header.putShort(1)",
    "                    header.putShort(channels.toShort())",
    "                    header.putInt(sampleRate)",
    "                    header.putInt(byteRate)",
    "                    header.putShort((channels * bitsPerSample / 8).toShort())",
    "                    header.putShort(bitsPerSample.toShort())",
    "                    header.put(\"data\".toByteArray())",
    "                    header.putInt(pcmSize.toInt())",
    "                    out.write(header.array())",
    "                    FileInputStream(tmpFile).use { inp -> inp.copyTo(out) }",
    "                }",
    "                promise.resolve(outputPath)",
    "            } catch (e: Exception) {",
    "                outFile.delete()",
    "                promise.reject(\"WMA_ERROR\", e.message ?: \"Unknown error\")",
    "            } finally {",
    "                try { codec?.stop() } catch (_: Exception) {}",
    "                try { codec?.release() } catch (_: Exception) {}",
    "                extractor?.release()",
    "                tmpFile.delete()",
    "            }",
    "        }.start()",
    "    }",
    "}",
    "",
].join("\n");

var WMA_PACKAGE_KT = [
    "package com.nasosan.nasosanplayer",
    "",
    "import com.facebook.react.ReactPackage",
    "import com.facebook.react.bridge.NativeModule",
    "import com.facebook.react.bridge.ReactApplicationContext",
    "import com.facebook.react.uimanager.ViewManager",
    "",
    "class WmaPlayerPackage : ReactPackage {",
    "    override fun createNativeModules(ctx: ReactApplicationContext): List<NativeModule> =",
    "        listOf(WmaPlayerModule(ctx))",
    "    override fun createViewManagers(ctx: ReactApplicationContext): List<ViewManager<*, *>> =",
    "        emptyList()",
    "}",
    "",
].join("\n");

function withKotlinFiles(config) {
    return withDangerousMod(config, ["android", function(config) {
        var dir = path.join(
            config.modRequest.platformProjectRoot,
            "app/src/main/java/com/nasosan/nasosanplayer"
        );
        fs.mkdirSync(dir, { recursive: true });
        // Rimuove solo file obsoleti
        ["NasoSanBrowserService.kt"].forEach(function(f) {
            var p = path.join(dir, f);
            if (fs.existsSync(p)) fs.unlinkSync(p);
        });
        fs.writeFileSync(path.join(dir, "NasoSanPlaybackService.kt"), PLAYBACK_SERVICE_KT, "utf8");
        fs.writeFileSync(path.join(dir, "NasoSanPlayerModule.kt"), PLAYER_MODULE_KT, "utf8");
        fs.writeFileSync(path.join(dir, "NasoSanPlayerPackage.kt"), PLAYER_PACKAGE_KT, "utf8");
        fs.writeFileSync(path.join(dir, "NasoSanTrackCache.kt"), NASOSAN_TRACK_CACHE_KT, "utf8");
        fs.writeFileSync(path.join(dir, "TrackCacheModule.kt"), TRACK_CACHE_MODULE_KT, "utf8");
        fs.writeFileSync(path.join(dir, "TrackCachePackage.kt"), TRACK_CACHE_PACKAGE_KT, "utf8");
        fs.writeFileSync(path.join(dir, "CarModeModule.kt"), CAR_MODE_MODULE_KT, "utf8");
        fs.writeFileSync(path.join(dir, "CarModePackage.kt"), CAR_MODE_PACKAGE_KT, "utf8");
        fs.writeFileSync(path.join(dir, "SpeechnotesWidgetModule.kt"), SPEECHNOTES_WIDGET_MODULE_KT, "utf8");
        fs.writeFileSync(path.join(dir, "SpeechnotesWidgetViewManager.kt"), SPEECHNOTES_WIDGET_VIEW_MANAGER_KT, "utf8");
        fs.writeFileSync(path.join(dir, "SpeechnotesWidgetPackage.kt"), SPEECHNOTES_WIDGET_PACKAGE_KT, "utf8");
        return config;
    }]);
}

// ── 5. MainApplication patch ──────────────────────────────────────────────────
function withMainAppPatch(config) {
    return withDangerousMod(config, ["android", function(config) {
        var p = path.join(
            config.modRequest.platformProjectRoot,
            "app/src/main/java/com/nasosan/nasosanplayer/MainApplication.kt"
        );
        if (!fs.existsSync(p)) return config;
        var src = fs.readFileSync(p, "utf8");
        // Rimuove vecchie registrazioni (prevenzione duplicati)
        src = src.replace(/\s*add\(NasoSanPlayerPackage\(\)\)/g, "");
        src = src.replace(/\s*add\(TrackCachePackage\(\)\)/g, "");
        src = src.replace(/\s*add\(CarModePackage\(\)\)/g, "");
        src = src.replace(/\s*add\(WmaPlayerPackage\(\)\)/g, "");
        src = src.replace(/\s*add\(SpeechnotesWidgetPackage\(\)\)/g, "");
        // Aggiunge tutti i package
        if (src.includes("PackageList(this).packages.apply {")) {
            src = src.replace(
                "PackageList(this).packages.apply {",
                "PackageList(this).packages.apply {\n            add(NasoSanPlayerPackage())\n            add(TrackCachePackage())\n            add(CarModePackage())\n            add(SpeechnotesWidgetPackage())"
            );
        } else {
            src = src.replace(
                "val packages = PackageList(this).packages",
                "val packages = PackageList(this).packages\n                packages.add(NasoSanPlayerPackage())\n                packages.add(TrackCachePackage())\n                packages.add(CarModePackage())\n                packages.add(SpeechnotesWidgetPackage())"
            );
        }
        fs.writeFileSync(p, src, "utf8");
        return config;
    }]);
}

module.exports = function withMedia3Player(config) {
    config = withGradleDeps(config);
    config = withManifest(config);
    config = withAutomotiveXml(config);
    config = withKotlinFiles(config);
    config = withMainAppPatch(config);
    return config;
};
